WITH project_map AS (
SELECT * FROM VALUES
    ('HTAN2_Glioma', 63298048),
    ('HTAN2_Gastric', 63298051),
    ('HTAN2_Ovarian', 63298044),
    ('HTAN2_Pediatric', 63298059),
    ('HTAN2_Myeloma', 63298063),
    ('HTAN2_Prostate', 63298068),
    ('HTAN2_Pancreatic', 63298065),
    ('HTAN2_Colorectal', 63298073),
    ('HTAN2_Lymphoma', 63298076),
    ('HTAN2_Skin', 63298054),
    ('htan2-testing1', 63834783)
AS project_map (PROJECT_NAME, PROJECT_ID)
)

SELECT 
n.ID AS FILE_ID,
n.NAME AS FILE_NAME,
n.CREATED_ON,
n.CREATED_BY AS CREATED_BY_ID,
u.USER_NAME AS CREATED_BY_USERNAME,
COALESCE(ARRAY_SIZE(OBJECT_KEYS(n.ANNOTATIONS:"annotations")), 0) AS ANNOTATION_COUNT,
n.PROJECT_ID,
p.PROJECT_NAME,
n.BENEFACTOR_ID,
n.PARENT_ID,
COALESCE(b.NAME, p.PROJECT_NAME) AS PARENT_NAME,
COALESCE(b.NODE_TYPE,'project') AS PARENT_TYPE
FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.NODE_LATEST n
JOIN project_map p
ON n.PROJECT_ID = p.PROJECT_ID
LEFT JOIN SYNAPSE_DATA_WAREHOUSE.SYNAPSE.NODE_LATEST b
ON n.PARENT_ID = b.ID
LEFT JOIN SYNAPSE_DATA_WAREHOUSE.SYNAPSE.USERPROFILE_LATEST u
ON n.CREATED_BY = u.ID
WHERE n.CREATED_ON >= DATEADD(day, -365, CURRENT_TIMESTAMP())
ORDER BY n.CREATED_ON DESC;